databases:
  - name: AI_dialogue_app_DB
    databaseName: ai_dialogue_app_4tve
    user: AI_dialogue_app
    region: singapore

services:
  - type: web
    name: AI_dialogue_app
    runtime: docker
    region: singapore
    branch: master
    plan: free
    dockerfilePath: ./Dockerfile
    domains:
      - ai-dialogue.jp
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AI_dialogue_app_db
          property: connectionString

